### ISSUE TITLE
Easy to fix docs corrections

### ISSUE THREAD

**Issue by xrdy511623** [jupyterhub/nativeauthenticator#113]
### Bug description
in the jupyterhub_config.py, I set `c.Authenticator.add_two_factor_authentication = True`. However，
while I start jupyterhub service, a warning occurs that Config option `add_two_factor_authentication` not recognized by `NativeAuthenticator`. Anyone who knows where I went wrong?

## Expected behaviour
I except the configuration that  c.Authenticator.add_two_factor_authentication = True would take effect.

## Actual behaviour
As a result,  a warning occurs that Config option `add_two_factor_authentication` not recognized by `NativeAuthenticator`.

**Comment by xrdy511623** [comment]
I have read the source code , now I know that the official documentation is wrong. The source code like this:
allow_2fa = Bool(
        False,
        config=True,
        help=""
    )

class SignUpHandler(LocalBase):
    """Render the sign in page."""
    async def get(self):
        if not self.authenticator.enable_signup:
            raise web.HTTPError(404)

        self._register_template_path()
        html = self.render_template(
            'signup.html',
            ask_email=self.authenticator.ask_email_on_signup,
            two_factor_auth=self.authenticator.allow_2fa,
        )
        self.finish(html)

Hence, If you set c.Authenticator.allow_2fa = True, the problem should be solved.

**Comment by consideRatio** [comment]
@xrdy511623 thanks for writing an issue about this and summarizing what the solution was! I'm opening it again until the documentation is fixed.

## Issue summary

The documentation here use the wrong configuration name (`add_two_factor_authentication`), it should be `allow_2fa`.

https://github.com/jupyterhub/nativeauthenticator/blob/e66ef4055c918c135e569b81d22949b6c6e551a4/docs/options.rst#L122

**Comment by xrdy511623** [comment]
Also, the options.rst on minimum password length is wrong, which sets the attribute like this:
c.Authenticator.minimim_password_length = 10

However, it can not be recognized by nativeauthenticator for spelling mistake, the correct setting should be like this:

c.Authenticator.minimum_password_length = 10
