### ISSUE TITLE
Add `allowed_users` to authorized_users automatically?

### ISSUE THREAD

**Issue by mhwasil** [jupyterhub/nativeauthenticator#116]
Hi everyone,
I am currently using nativeauthentication for a large number of users, it would be easier to just automatically add `whitelist(deprecated) or allowed_users` of jupyterhub users to the authorized users.
I will make a PR this makes sense for the nativeauthenticator.

Cheers

**Comment by lambdaTotoro** [comment]
Yes, this is a very sensible suggestion and was also easy to implement. I'll merge the branch momentarily. Thanks for pointing that out!
