### ISSUE TITLE
User is not remove from jupyterhub database at discard

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/nativeauthenticator#122]
When a user is discard the function jupyterhub.auth.delete_user(user) is called, but this function only remove user from jupyterhub whitelist but it doesn't remove the user from jupyterhub database.

https://github.com/jupyterhub/jupyterhub/blob/2a1d3415864fa945e13852a1cb5bf8199b9aea72/jupyterhub/auth.py#L613

Regards

**Comment by lambdaTotoro** [comment]
You're correct, this reproduces. On it.

**Comment by djangoliv** [comment]
Maybe, if it is not possible to simpler delete the user, the discard button should not be displayed if the user has already been authorized ?

**Comment by lambdaTotoro** [comment]
It is possible and it happens properly now, I just didn't consider that the user might already be in the other table when being discarded when I wrote the feature.

**Comment by toccalenuvole73** [comment]
how can i completely remove a user? 
I noticed tons of this log:

mag 22 20:11:16 v01gp2-jupyterhub.sphostserver.com python3[676]: [I 2021-05-22 20:11:16.489 JupyterHub log:189] 302 GET /hub/user/user@gmail.com/healthz -> /hub/login?next=%2Fhub%2Fuser%2Fuser%40gmail.com%2Fhealthz (@37.117.83.60) 0.88ms
mag 22 20:11:19 v01gp2-jupyterhub.sphostserver.com python3[676]: [I 2021-05-22 20:11:19.675 JupyterHub log:189] 302 GET /user/user@gmail.com/healthz -> /hub/user/user@gmail.com/healthz (@37.117.83.60) 0.92ms
mag 22 20:11:19 v01gp2-jupyterhub.sphostserver.com python3[676]: [I 2021-05-22 20:11:19.736 JupyterHub log:189] 302 GET /hub/user/user@gmail.com/healthz -> /hub/login?next=%2Fhub%2Fuser%2Fuser%40gmail.com%2Fhealthz (@37.117.83.60) 0.84ms

and can't log in. So I tryed to delete that specific user from auth page and linux...but it's still there in the log!
