### ISSUE TITLE
Tornado Error while moving to signup page

### ISSUE THREAD

**Issue by jainnishant** [jupyterhub/nativeauthenticator#130]
### Bug description
Getting 500 : Internal Server Error when trying to signup using Native Authenticator
#### Expected behaviour
Sign up page should appear
#### Actual behaviour
Getting 500 : Internal Server Error

### Your personal set up

 Using jupyterhub docker to run with nativeauthenticator

jupyterhub_config.py contents

c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
c.Authenticator.check_common_password = True
c.Authenticator.minimum_password_length = 10
c.Authenticator.allowed_failed_logins = 3
c.Authenticator.seconds_before_next_try = 600
c.Authenticator.ask_email_on_signup = True

Error Details in logs : 

[I 2021-01-05 10:33:03.073 JupyterHub log:181] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@::ffff:172.17.0.1) 1.02ms
[D 2021-01-05 10:33:03.093 JupyterHub handlers:22] Adding /usr/local/lib/python3.8/dist-packages/nativeauthenticator/templates to template path
[I 2021-01-05 10:33:03.135 JupyterHub log:181] 200 GET /hub/login?next=%2Fhub%2F (@::ffff:172.17.0.1) 42.94ms
[E 2021-01-05 10:33:08.734 JupyterHub web:1789] Uncaught exception GET /hub/signup (::ffff:172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/hub/signup', version='HTTP/1.1', remote_ip='::ffff:172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/nativeauthenticator/handlers.py", line 41, in get
        self.finish(html)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 172, in finish
        super().finish(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1127, in finish
        self.write(chunk)
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 841, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
    
[D 2021-01-05 10:33:08.737 JupyterHub base:1280] No template for 500
[E 2021-01-05 10:33:08.769 JupyterHub log:173] {
      "X-Forwarded-Host": "127.0.0.1:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:172.17.0.1",
      "Cookie": "jupyterhub-session-id=[secret]; _xsrf=[secret]",
      "Accept-Language": "en-GB,en-IN;q=0.9,en-US;q=0.8,en;q=0.7,hi;q=0.6",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "http://127.0.0.1:8000/hub/login?next=%2Fhub%2F",
      "Sec-Fetch-Site": "same-origin",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "127.0.0.1:8000"
    }

</details>

**Comment by djangoliv** [comment]
Can you test this pull request: https://github.com/jupyterhub/nativeauthenticator/pull/129 ?
I think this is the same problem.

**Comment by jainnishant** [comment]
Hi @djangoliv 

I have tested the request and this resolves the issue but now, I cant get to the approval workflow from admins

**Comment by jainnishant** [comment]
@djangoliv : When can we merge this and push out a new version?

**Comment by djangoliv** [comment]
@jainnishant I do not know :)
@lambdaTotoro What is your opinion on it? I also have to use this PR in production.

**Comment by lambdaTotoro** [comment]
I've left a few comments on the PR, tl;dr is that that fixes it for `jupyterhub==1.3.0` but breaks it for older versions. So it's not a trivial green light. I'll look into it further.

**Comment by lambdaTotoro** [comment]
We merged the pull request and released a new version a few days ago, can anyone confirm this issue is no longer current?

**Comment by djangoliv** [comment]
I have successfully switched to master since the PR was merged. Thanks.
