### ISSUE TITLE
How to create the first/init admin account and password

### ISSUE THREAD

**Issue by imdodolook** [jupyterhub/nativeauthenticator#140]
Hi nativeauthenticator team, I am new here. I tried the dummy authenticator before, and am thinking to use native authenticator now.
The admin user and password are predefined in the jupyterhub configure file for dummy authenticator. So how can I create /pre-define the first admin account with username password for native authenticator?

I searched many documents about the nativeauthenticator, they all said the admin account need also be singed up. I didn't find the place to sign up the admin account( only find the way to sing up normal account) and any clue about it .

To be clear , my questions is 
1. how can I create the very first admin account with password?
2. how can I create other admin account ?
3. I am running with non-root access in redhat, so I didnt create any user on it, is it nessary to create some linux account and use it as admin account?

Thanks

**Comment by muru** [comment]
Use the same page for signing up for "normal" users - if your username is the list of admin users, you will be automatically approved. See this section of the docs:

> It is important to notice that admin must also create a new user through signup. However, **usernames list in the config file as admins will automatically have authorization** to enter the system.

**Comment by ibayer** [comment]
@muru 
Thanks for your feedback. I'm exactly in the same situation (more details in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/295) but my admin user doesn't seem to be automatically approved. He is listed in the config file and can be used without nativeauthenticator.

Can you give me any hints on how to debug this?

**Comment by ibayer** [comment]
Look like I had a tljh specific issue that I have been able to resolve https://github.com/jupyterhub/the-littlest-jupyterhub/issues/295#issuecomment-803295915, thanks for providing NativeAuthenticator!

**Comment by iamalonso** [comment]
Hi, I'm using the Native Authenticator with Docker Compose. In my Dockerfile I put this:

`FROM jupyterhub/jupyterhub

# Download and install Anaconda
COPY config/Anaconda3-2020.11-Linux-x86_64.sh /tmp/.
RUN bash /tmp/Anaconda3-2020.11-Linux-x86_64.sh -b
RUN rm /tmp/Anaconda3-2020.11-Linux-x86_64.sh
ENV PATH=/root/anaconda3/bin:$PATH
RUN conda --version
RUN conda init
RUN apt-get update && apt-get install -y \
        git \
        nano \
        vim \
        && rm -rf /var/lib/apt/lists/*

# Installing NativeAuthenticator
COPY jupyterhub_config.py /srv/jupyterhub/.
RUN git clone https://github.com/jupyterhub/nativeauthenticator.git
WORKDIR nativeauthenticator
RUN pip install -e .

# Other dependencies
RUN conda install -c conda-forge ruamel.yaml
WORKDIR /home/aysenadmin`

My jupyterhub_config.py file looks like this:
`mport pwd, subprocess
c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
c.Authenticator.admin_users = {'admin'}
def pre_spawn_hook(spawner):
    username = spawner.user.name
    try:
        pwd.getpwnam(username)
    except KeyError:
        subprocess.check_call(['useradd', '-ms', '/bin/bash', username])
c.Spawner.pre_spawn_hook = pre_spawn_hook
c.Spawner.default_url = '/home/aysenadmin'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_connect_ip = 'jupyterhub'`

The container up without problems but when I try access to the /hub/signup route I got the message:

404 : Not Found
Jupyter has lots of moons, but this is not one...

Could you guys advise me please?

**Comment by imdodolook** [comment]
You are right, the admin sign up will be auto approved, my issue is resolved, sorry to keep this issue open so long, I have some issue to access my account.
