### ISSUE TITLE
Link to docs in GitHub repo about section

### ISSUE THREAD

**Issue by manics** [jupyterhub/nativeauthenticator#143]
### Proposed change
The `About` section in the right-hand side-bar of the repository's main page should have a URL field.
Set this to https://native-authenticator.readthedocs.io/ so people can go there straight away instead of reading through the README to find it
![image](https://user-images.githubusercontent.com/1644105/111842705-c64a7480-88f7-11eb-9a16-a7acdfccc349.png)

### (Optional): Suggest a solution
Set the URL in the GitHub repo about section :smile_cat:

**Comment by lambdaTotoro** [comment]
Done!
