### ISSUE TITLE
Provide permissions to upload releases to PyPI for use in our CI system

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/nativeauthenticator#144]
Across the JupyterHub org we have made cutting releases of projects to PyPI, npm, etc be automated based on pushing git tags. This project hasn't such automation fully setup yet though. What's missing is the permission to do it.

@lambdaTotoro @leportella you are currently the only maintainers of the PyPI package at https://pypi.org/project/jupyterhub-nativeauthenticator/, could you add permissions to manage the project to the jupyterhub-bot?

### Suggested action points
- [x] Add https://pypi.org/user/jupyterhub-bot/ as a maintainer of https://pypi.org/project/jupyterhub-nativeauthenticator/ (@leportella, @lambdaTotoro)
- [x] Add a deployment token for the jupyterhub-bot dedicated for pushing releases of jupyterhub-nativeauthenticator to PyPI (@consideRatio)
- [x] Add GitHub secret `PYPI_PASSWORD` referenced by [the publish workflow](https://github.com/jupyterhub/nativeauthenticator/blob/master/.github/workflows/publish.yaml#L33-L37) at https://github.com/jupyterhub/nativeauthenticator/settings/secrets/actions (@consideRatio)

**Comment by lambdaTotoro** [comment]
I sadly can't add you or the bot as maintainer, I think only @leportella can. Same goes for your asks in #133, if those are still current. I've written her in case she has her GitHub Notifications off. I'll let you know as soon as there's a development.

**Comment by consideRatio** [comment]
Wiee thanks @leportella this is now completed!
