### ISSUE TITLE
crypto directory not installed?

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/nativeauthenticator#156]
### Bug description
When installing off github the crypto directory is not installed.

#### Expected behaviour
The crypto directory be installed.

#### Actual behaviour
The crypto directory is not installed.

### How to reproduce
1. `virtualenv -p python3 ~/venv/test`
2. `source ~/venv/test/bin/activate`
3. `pip install git+https://github.com/jupyterhub/nativeauthenticator.git@1.0.3`
3. `ls ~/venv/test/lib/python3.6/site-packages/nativeauthenticator/`
4. Notice the missing directory which will cause the import to fail

### Your personal set up
Tried with
* `Python 3.6.9` under `git version 2.17.1`
* `Python 3.8.10` under `git version 2.25.1`

both cases with the latest pip `21.3`

Doing a `git clone` or `pip install -e git+https://github.com/jupyterhub/nativeauthenticator.git@1.0.3#egg=jupyterhub-nativeauthenticator` works as expected

@lambdaTotoro

**Comment by lambdaTotoro** [comment]
I have also noticed this recently, but I'm not sure how to fix it. Do you know?

**Comment by lambdaTotoro** [comment]
Ah, that could well be it. Thanks for looking into it. I'll try if I can't generate an egg/wheel locally and test with that. 

> I'd hate to make other small mistakes and pull that version higher and higher for petty reasons.
I mean, that ship has already sailed, but we don't need to make it worse.

**Comment by lambdaTotoro** [comment]
I tested that locally and your solution works. As in, the generated wheel has no crypto module without the file and does have one, if an empty one is present. I'll fix that up.

**Comment by davidedelvento** [comment]
I confirm that it works perfectly for me too! 
Thank you for your patience and quick response to get this fixed!
Looking forward to using this in production deployments, yay!
