### ISSUE TITLE
/hub/authorize's Discard button - what does it do and how does that work?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/nativeauthenticator#164]
I'm not sure how the Discard button function, I understand it means that one has discarded the authorization request and such, but if the user has already been created - then what happens? Can a user sign up again with that username and acquire control of remnant data for example?

**Comment by lambdaTotoro** [comment]
I've written a bit more on this in the documentation (not enough to warrant an entire PR, though) in commit a35fcc4fc3565665c4de46d757a39807239c83d9. Do you think it's clear enough now to close this issue?

**Comment by consideRatio** [comment]
Absolutely!

**Comment by consideRatio** [comment]
> not enough to warrant an entire PR, though

Have you tried creating PRs via the `gh` CLI? It goes so fast that I almost always use PRs without thinking it adds work.

I appreciate the simplicity to review the changes made to this repo. Hmm, thinking about it, perhaps you could start doing it systematically? Since this is a project that bundles into Z2JH + TLJH distributions, it would feel good to assume a pushed commit without a PR is something suspicious to look into rather than a common practice that can be overlooked - assuming for example someone compromised your account.

**Comment by lambdaTotoro** [comment]
So the threat model is someone smart or lucky enough to compromise both my ssh and PGP keys and introduces a backdoor or other deliberate vulnerability into this project? And the way to spot that is that they would just push things to main without PRs?

I don't know, that sounds like a lot of tedium for tiny changes like the recent typo commit for a quite remote possibility.

I'll ponder it more on it tomorrow.

**Comment by consideRatio** [comment]
Hmm... I don't understand the details about PGP keys. I guess though my request was mainly stemming from me feeling more comfortable reviewing all changes systematically via notifications from watching the repo.

**Comment by lambdaTotoro** [comment]
> I don't understand the details about PGP keys

What I meant was that I sign all my commits with my PGP key. You can see that I did from the "Verified" badge next to [my commits](https://github.com/jupyterhub/nativeauthenticator/commits/main). People wanting to fake that would either need to compromise my PGP key or get into my GitHub Account, which is behind 2-Factor Authentication. 

Point is, I don't think deprecating non-merge commits to main does anything at all for security. But of course there are other reasons why one might want to do that. I talked to a trusted friend of mine and he was of your opinion as well, so I'll adapt to that.

**Comment by consideRatio** [comment]
Thank you @lambdaTotoro, sorry for being pushy about this!
