### ISSUE TITLE
Setup documentation with sphinx

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/nativeauthenticator#2]
We should write documentation for this from the very beginning. We use [Sphinx](http://www.sphinx-doc.org/en/master/) for the docs, so this task is to set up a basic sphinx setup that can build on [read the docs](https://readthedocs.org/).

- [x] Follow the [Read The Docs Quickstart](https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html) to set up sphinx
- [x] Setup Read The Docs to automatically build our documentation

**Comment by willingc** [comment]
Welcome @leportella. Great to see you working on JupyterHub. Happy to help you (or others) who work on this issue. :wave:

**Comment by leportella** [comment]
Thank you @willingc ! So thrilled to be working with you all :)
