### ISSUE TITLE
Create a panel so admin can manage authorization of users

### ISSUE THREAD

**Issue by leportella** [jupyterhub/nativeauthenticator#20]
- [x] Create a new endpoint for admin 
- [x] Verify admin privileges to access new endpoint
- [x] Add list of users on the system
- [x] Allow to authorize users that had signed up to enter the system

**Comment by leportella** [comment]
I am not sure if we can improve the current admin panel or create a new one specifically for this project. What do you think @yuvipanda ?

**Comment by yuvipanda** [comment]
@leportella I think we should create newer one for the specific purpose of 'approving pending users' only, since the default panel already lets users start / stop / delete users. So we can call it 'approval queue' or something rather than 'admin panel'

**Comment by leportella** [comment]
Closed by #29
