### ISSUE TITLE
Release needed for JupyterHub 2 and 3 compatibility

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/nativeauthenticator#214]
#160 was merged just after 1.0.5 was released, and we need a release including it for functionality with JupyterHub 2 and 3. The JupyterHub Helm chart in https://github.com/jupyterhub/zero-to-jupyterhub-k8s will include JupyterHub 3 so users of nativeauthenticator can't upgrade to it unless a patch is released.

Generating a changelog using `github-activity` I saw the following PRs merged since 1.0.5. Is any change here a breaking change that merits a 2.0.0 release? Otherwise, it should be a 1.1.0 release as it includes enhancements etc rather than just documentation/bugfixes.

### 1.0.5...master@{2022-08-25}

([full changelog](https://github.com/jupyterhub/nativeauthenticator/compare/1.0.5...37a5c71749651d406fb9d7e1196321a601226e83))

#### Enhancements made

- Ask for new passwords twice, ask for current password on change [#180](https://github.com/jupyterhub/nativeauthenticator/pull/180) ([@lambdaTotoro](https://github.com/lambdaTotoro))

#### Bugs fixed

- Add slash restriction to username validation [#197](https://github.com/jupyterhub/nativeauthenticator/pull/197) ([@marc-marcos](https://github.com/marc-marcos))
- Correct login procedure for admins [#195](https://github.com/jupyterhub/nativeauthenticator/pull/195) ([@lambdaTotoro](https://github.com/lambdaTotoro))
- Enforce password criteria on password change [#169](https://github.com/jupyterhub/nativeauthenticator/pull/169) ([@lambdaTotoro](https://github.com/lambdaTotoro))
- Systematic refresh of templates [#162](https://github.com/jupyterhub/nativeauthenticator/pull/162) ([@consideRatio](https://github.com/consideRatio))

#### Maintenance and upkeep improvements

- document and refactor the handlers [#183](https://github.com/jupyterhub/nativeauthenticator/pull/183) ([@lambdaTotoro](https://github.com/lambdaTotoro))
- chore: use async instead of gen.coroutine [#178](https://github.com/jupyterhub/nativeauthenticator/pull/178) ([@consideRatio](https://github.com/consideRatio))
- pre-commit: apply black formatting [#174](https://github.com/jupyterhub/nativeauthenticator/pull/174) ([@consideRatio](https://github.com/consideRatio))
- Smaller tweaks from pre-commit autoformatting hooks [#173](https://github.com/jupyterhub/nativeauthenticator/pull/173) ([@consideRatio](https://github.com/consideRatio))
- Support JupyterHub 2's fine grained RBAC permissions, and test against Py3.10 and JH2 [#160](https://github.com/jupyterhub/nativeauthenticator/pull/160) ([@consideRatio](https://github.com/consideRatio))

#### Documentation improvements

- update documentation screenshots [#194](https://github.com/jupyterhub/nativeauthenticator/pull/194) ([@lambdaTotoro](https://github.com/lambdaTotoro))
- docs: fix c.JupyterHub.template_paths [#192](https://github.com/jupyterhub/nativeauthenticator/pull/192) ([@yapatta](https://github.com/yapatta))
- docs: c.NativeAuthenticator instead of c.Authenticator [#188](https://github.com/jupyterhub/nativeauthenticator/pull/188) ([@consideRatio](https://github.com/consideRatio))
- docs: update from rST to MyST and to common theme [#187](https://github.com/jupyterhub/nativeauthenticator/pull/187) ([@consideRatio](https://github.com/consideRatio))
- document and refactor the handlers [#183](https://github.com/jupyterhub/nativeauthenticator/pull/183) ([@lambdaTotoro](https://github.com/lambdaTotoro))
- docs: add inline documentation to orm.py [#179](https://github.com/jupyterhub/nativeauthenticator/pull/179) ([@consideRatio](https://github.com/consideRatio))
- Update CONTRIBUTING.md [#161](https://github.com/jupyterhub/nativeauthenticator/pull/161) ([@consideRatio](https://github.com/consideRatio))

#### Continuous integration improvements

- ci: rely on pre-commit.ci & run tests only if needed [#175](https://github.com/jupyterhub/nativeauthenticator/pull/175) ([@consideRatio](https://github.com/consideRatio))

**Comment by consideRatio** [comment]
@lambdaTotoro now JupyterHub 3.0.0 is out and z2jh 2.0.0 could be released today, but nativeauthenticator will be broken with that version bump of JupyterHub from JupyterHub 1 to JupyterHub 3 made in the z2jh distribution of JupyterHub.

Is it okay if I'll go for a release of nativeauthenticator in its current state?

**Comment by lambdaTotoro** [comment]
Yes, go ahead. I would have liked to incorporate a few things still, but I didn't get to them in time and this is more important.
