### ISSUE TITLE
Planning for release 1.2.0 - JupyterHub 4 compatibility

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/nativeauthenticator#241]
I'd like to see a new release cut with the JupyterHub 4 compatibility added via #236 and #239, for z2jh 3.0.0 and tljh 1.0.0 releases.

### Not blocking, but needs a review

- #221
- #223

**Comment by lambdaTotoro** [comment]
I have a move coming up and will not have spare brain power available until mid June at the earliest. I am happy with you using your own best judgement, though. Feel free to go ahead as needed.
