### ISSUE TITLE
Set template problem that style is error

### ISSUE THREAD

**Issue by linmeimei0512** [jupyterhub/nativeauthenticator#269]
### Bug description

I set configuration of templates by
```
c.JupyterHub.template_paths = [f"{os.path.dirname(nativeauthenticator.__file__)}/templates/"]
```

But that style is some error.  
![image](https://github.com/jupyterhub/nativeauthenticator/assets/14798636/36b66a55-aa59-4926-a77a-11c1ddddd24c)

How can I fix this problem?  
  
### My environment is:
 - OS: Ubuntu 20.04
 - Jupyterhub version: jupyterhub/jupyterhub:5

**Comment by manics** [comment]
Fixed by https://github.com/jupyterhub/nativeauthenticator/pull/270
