### ISSUE TITLE
Authorize user does not work when using c.JupyterHub.base_url

### ISSUE THREAD

**Issue by FlorianLautenschlager** [jupyterhub/nativeauthenticator#84]
Hi there 👋 

I set up TLJH and configured the nativeauthenticator and also the c.JupyterHub.base_url="jupyter". Hence Jupyterhub is running under `../jupyter/hub/...`
Everything is working except, that I (as an admin) can not authorize users via `/jupyter/hub/authorize` as in the `autorization-area.html` 
the path is hardcoded and does not respect the base path: https://github.com/jupyterhub/nativeauthenticator/blob/c092d6cede21f997c4886419e47a70ad59ef5920/nativeauthenticator/templates/autorization-area.html#L27-L38

Even if i add the `base_url` by hand I will be redirected to `/authorize` which can also not be found:
https://github.com/jupyterhub/nativeauthenticator/blob/c092d6cede21f997c4886419e47a70ad59ef5920/nativeauthenticator/handlers.py#L112

Best Regards,
Florian

**Comment by 2JS** [comment]
Same issue here with c.JupyterHub.bind_url="jupyter"

**Comment by leportella** [comment]
We just merged a pull request to fix it and it should be fixed on version 0.0.5
