### ISSUE TITLE
Endpoint to reset passwords?

### ISSUE THREAD

**Issue by lambdaTotoro** [jupyterhub/nativeauthenticator#90]
I'm using jupyterHub with nativeauthenticator and I have a user who apparently mistyped their password on signup and now doesn't know what to do. 
I know there is an endpoint to change your own password when logged in (#33), but I cannot find one for admins to change / reset a user's password. 

As a workaround, I think deleting the user and having them sign up with the same name should be an option, but a reset/change password option for admins should potentially also be considered (especially while #73 remains open).

**Comment by djangoliv** [comment]
I propose a PR for this 

https://github.com/jupyterhub/nativeauthenticator/pull/112

**Comment by lambdaTotoro** [comment]
I merged said pull request, closing this issue.
