### ISSUE TITLE
Authorization urls don't respect JupyterHub base url

### ISSUE THREAD

**Issue by JohnPaton** [jupyterhub/nativeauthenticator#94]
If JupyterHub is deployed with a custom base url, the authorization urls don't respect it. 

Examples:
https://github.com/jupyterhub/nativeauthenticator/blob/master/nativeauthenticator/templates/autorization-area.html#L27
https://github.com/jupyterhub/nativeauthenticator/blob/master/nativeauthenticator/handlers.py#L112

These should take `c.JupyterHub.base_url` into account

**Comment by leportella** [comment]
Fixed
